begin;
select plan(9);
select testkit.create_user('93400000-0000-4000-8000-000000000001','designer-vat@test.local');
create temp table designer_vat_company as select testkit.provision('93400000-0000-4000-8000-000000000001','Designer VAT') id;
update public.companies set show_vat_breakdown_on_prints=true where id=(select id from designer_vat_company);
grant select on designer_vat_company to authenticated;
select testkit.as_user((select id from designer_vat_company),'93400000-0000-4000-8000-000000000001','Admin');
select is(public.save_document_design('receipt','{"version":1,"layout":"compact","message":"","showVatBreakdown":false,"custom":{"label":"","value":"","display":"text"}}')->>'showVatBreakdown','false','receipt can hide VAT independently');
select is(public.save_document_design('invoice','{"version":1,"layout":"modern","message":"","showVatBreakdown":true,"custom":{"label":"","value":"","display":"text"}}')->>'showVatBreakdown','true','invoice can show VAT independently');
select is((select show_vat_breakdown_on_prints from public.companies where id=public.current_company_id()),true,'document presentation never changes company accounting or shared preference');
select throws_ok($$select public.save_document_design('receipt','{"version":1,"layout":"classic","message":"","showVatBreakdown":"false","custom":{"label":"","value":"","display":"text"}}')$$,'P0001','invalid_document_design','string override rejected');
select throws_ok($$select public.save_document_design('receipt','{"version":1,"layout":"classic","message":"","showVatBreakdown":null,"custom":{"label":"","value":"","display":"text"}}')$$,'P0001','invalid_document_design','null override rejected');
select is((select document_designs#>>'{invoice,layout}' from public.companies where id=public.current_company_id()),'modern','other document remains unchanged');
select lives_ok($$select public.save_document_design('proforma','{"version":1,"layout":"classic","message":"","custom":{"label":"","value":"","display":"text"}}')$$,'legacy design without override remains valid');
reset role;
insert into public.customers(id,company_id,first_name) select '93400000-0000-4000-8000-000000000010',id,'Buyer' from designer_vat_company;
insert into public.external_document_links(company_id,party_id,document_type,subject_id,token_hash,snapshot,expires_at)
select id,'93400000-0000-4000-8000-000000000010','receipt','93400000-0000-4000-8000-000000000011',encode(extensions.digest('designer-vat-public','sha256'),'hex'),'{}',now()+interval '1 day' from designer_vat_company;
set local role anon;
select is(public.public_external_document('designer-vat-public')#>>'{document_design,showVatBreakdown}','false','public document captures its presentation override');
reset role;
select testkit.as_user((select id from designer_vat_company),'93400000-0000-4000-8000-000000000001','Admin');
select public.save_document_design('receipt','{"version":1,"layout":"compact","message":"","showVatBreakdown":true,"custom":{"label":"","value":"","display":"text"}}');
reset role;
set local role anon;
select is(public.public_external_document('designer-vat-public')#>>'{document_design,showVatBreakdown}','false','already-issued document retains its saved presentation');
reset role;
select * from finish();
rollback;
