import {
  ApplicationConfig,
  isDevMode,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideServiceWorker } from '@angular/service-worker';
import { provideNgIconsConfig, provideIcons } from '@ng-icons/core';
import {
  heroArchiveBox,
  heroReceiptRefund,
  heroBell,
  heroBellAlert,
  heroBellSlash,
  heroChatBubbleOvalLeftEllipsis,
  heroCheck,
  heroChevronDoubleLeft,
  heroChevronDoubleRight,
  heroChevronRight,
  heroDevicePhoneMobile,
  heroEnvelope,
  heroExclamationTriangle,
  heroMagnifyingGlass,
  heroArrowsRightLeft,
  heroArrowPath,
  heroArrowDownTray,
  heroArrowUpTray,
  heroArrowRight,
  heroArrowRightOnRectangle,
  heroBanknotes,
  heroBars3,
  heroCalendarDays,
  heroCamera,
  heroChartBar,
  heroChatBubbleLeftRight,
  heroCheckBadge,
  heroCheckCircle,
  heroChevronDown,
  heroChevronLeft,
  heroChevronUp,
  heroClipboardDocumentList,
  heroCog6Tooth,
  heroCreditCard,
  heroCurrencyDollar,
  heroCube,
  heroDocumentText,
  heroEyeSlash,
  heroHome,
  heroInformationCircle,
  heroLockClosed,
  heroLockOpen,
  heroMoon,
  heroMinus,
  heroPlus,
  heroPencilSquare,
  heroPrinter,
  heroQueueList,
  heroShoppingCart,
  heroSignal,
  heroSignalSlash,
  heroSparkles,
  heroSun,
  heroTruck,
  heroUserGroup,
  heroUserCircle,
  heroUsers,
  heroWifi,
  heroXMark,
} from '@ng-icons/heroicons/outline';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(
      routes,
      withInMemoryScrolling({ scrollPositionRestoration: 'enabled', anchorScrolling: 'enabled' })
    ),
    // Icon registry (design system: Heroicons outline via <app-icon name="hero…">)
    provideNgIconsConfig({ size: '1rem' }),
    provideIcons({
      heroArrowPath,
      heroArrowDownTray,
      heroArrowUpTray,
      heroArrowRight,
      heroChatBubbleLeftRight,
      heroDocumentText,
      heroQueueList,
      heroArchiveBox,
      heroReceiptRefund,
      heroBell,
      heroBellAlert,
      heroBellSlash,
      heroChevronDoubleLeft,
      heroChevronDoubleRight,
      heroChevronRight,
      heroExclamationTriangle,
      heroMagnifyingGlass,
      heroArrowsRightLeft,
      heroArrowRightOnRectangle,
      heroBanknotes,
      heroBars3,
      heroCalendarDays,
      heroCamera,
      heroChartBar,
      heroCheckBadge,
      heroCheckCircle,
      heroChevronDown,
      heroChevronLeft,
      heroChevronUp,
      heroClipboardDocumentList,
      heroCog6Tooth,
      heroCreditCard,
      heroCurrencyDollar,
      heroCube,
      heroEyeSlash,
      heroHome,
      heroInformationCircle,
      heroLockClosed,
      heroLockOpen,
      heroMoon,
      heroMinus,
      heroPlus,
      heroPencilSquare,
      heroPrinter,
      heroShoppingCart,
      heroSignal,
      heroSignalSlash,
      heroSun,
      heroTruck,
      heroUserGroup,
      heroUserCircle,
      heroUsers,
      heroXMark,
      heroChatBubbleOvalLeftEllipsis,
      heroCheck,
      heroDevicePhoneMobile,
      heroEnvelope,
      heroSparkles,
      heroWifi,
    }),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
};
