import {
  ApplicationConfig,
  isDevMode,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideServiceWorker } from '@angular/service-worker';
import { provideNgIconsConfig, provideIcons } from '@ng-icons/core';
import {
  heroArchiveBox,
  heroReceiptRefund,
  heroBell,
  heroBellSlash,
  heroChevronDoubleLeft,
  heroChevronDoubleRight,
  heroChevronRight,
  heroExclamationTriangle,
  heroMagnifyingGlass,
  heroArrowsRightLeft,
  heroArrowRightOnRectangle,
  heroBanknotes,
  heroBars3,
  heroCalendarDays,
  heroChartBar,
  heroCheckBadge,
  heroCheckCircle,
  heroChevronLeft,
  heroClipboardDocumentList,
  heroCog6Tooth,
  heroCreditCard,
  heroCube,
  heroHome,
  heroMoon,
  heroPlus,
  heroPrinter,
  heroShoppingCart,
  heroSun,
  heroTruck,
  heroUserGroup,
  heroUsers,
  heroXMark,
} from '@ng-icons/heroicons/outline';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    // Icon registry (design system: heroicons outline via <ng-icon name="hero…">)
    provideNgIconsConfig({ size: '1rem' }),
    provideIcons({
      heroArchiveBox,
      heroReceiptRefund,
      heroBell,
      heroBellSlash,
      heroChevronDoubleLeft,
      heroChevronDoubleRight,
      heroChevronRight,
      heroExclamationTriangle,
      heroMagnifyingGlass,
      heroArrowsRightLeft,
      heroArrowRightOnRectangle,
      heroBanknotes,
      heroBars3,
      heroCalendarDays,
      heroChartBar,
      heroCheckBadge,
      heroCheckCircle,
      heroChevronLeft,
      heroClipboardDocumentList,
      heroCog6Tooth,
      heroCreditCard,
      heroCube,
      heroHome,
      heroMoon,
      heroPlus,
      heroPrinter,
      heroShoppingCart,
      heroSun,
      heroTruck,
      heroUserGroup,
      heroUsers,
      heroXMark,
    }),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
};
