import type { SupabaseClient } from 'npm:@supabase/supabase-js@2';
// @ts-ignore Generated by scripts/build-document-edge.mjs before deployment.
type DocumentRenderer = typeof import('./generated/documents.mjs');
import { DeliveryError, assertOutboundMessage, sendWhatsappDocument } from './message-providers.ts';

async function logoAsset(
  path: string | null | undefined,
  { preparePdfLogo, MAX_LOGO_BYTES }: DocumentRenderer
) {
  if (!path) return undefined;
  // Never fetch arbitrary snapshot URLs (SSRF). Logos are immutable objects in our bucket.
  if (/^[a-z]+:/i.test(path) || path.includes('..') || path.startsWith('/'))
    throw new DeliveryError('unsupported_logo_reference', true, false);
  const url = `${Deno.env.get('SUPABASE_URL')}/storage/v1/object/public/company-logos/${path.split('/').map(encodeURIComponent).join('/')}`;
  let bytes: Uint8Array;
  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(8000), redirect: 'error' });
    if (!response.ok) throw new DeliveryError('logo_unavailable', response.status === 404, false);
    if (Number(response.headers.get('content-length')) > MAX_LOGO_BYTES)
      throw new DeliveryError('logo_too_large', true, false);
    const reader = response.body!.getReader();
    const chunks: Uint8Array[] = [];
    let length = 0;
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      length += value.length;
      if (length > MAX_LOGO_BYTES) {
        await reader.cancel();
        throw new DeliveryError('logo_too_large', true, false);
      }
      chunks.push(value);
    }
    bytes = new Uint8Array(length);
    let offset = 0;
    for (const chunk of chunks) {
      bytes.set(chunk, offset);
      offset += chunk.length;
    }
  } catch (error) {
    if (error instanceof DeliveryError) throw error;
    throw new DeliveryError('logo_fetch_failed', false, false);
  }
  return preparePdfLogo(bytes);
}

/** One job per invocation bounds memory and runtime. PostgreSQL owns claims and recovery. */
export async function processSaleDocument(db: SupabaseClient, outboxId?: string): Promise<void> {
  const { data: job, error } = await db.rpc('claim_sale_document_delivery', {
    p_outbox_id: outboxId ?? null,
  });
  if (error) throw new Error('document_claim_failed');
  if (!job) return;
  const started = performance.now();
  let dispatchStarted = false;
  try {
    const s = job.snapshot;
    const identity = { scope: 'company' as const, companyName: job.company_name_snapshot };
    assertOutboundMessage('whatsapp', job.caption, identity);
    if (identity.companyName !== s.company_name?.trim()) {
      throw new DeliveryError('message_contract: document_identity_mismatch', true, false);
    }
    if (job.caption.length > 1024) {
      throw new DeliveryError('message_contract: caption_too_long', true, false);
    }
    // Empty recovery ticks and invalid requests must not initialize fonts/WASM.
    const initStarted = performance.now();
    // @ts-ignore Generated artifact; keep every runtime export behind this import.
    const renderer: DocumentRenderer = await import('./generated/documents.mjs');
    const rendererInitMs = performance.now() - initStarted;
    const logoStarted = performance.now();
    const logo = await logoAsset(s.company_logo_path, renderer);
    const logoMs = performance.now() - logoStarted;
    const renderStarted = performance.now();
    const bytes = await renderer.renderSnapshotPdf(
      s,
      {
        name: s.company_name,
        address: s.company_address,
        email: s.company_email,
        phone: s.company_whatsapp,
        website: s.company_website,
        taxNumber: s.tax_registration_number,
      },
      logo
    );
    const renderMs = performance.now() - renderStarted;
    const { data: allowed, error: beginError } = await db.rpc('begin_sale_document_dispatch', {
      p_outbox_id: job.id,
      p_claim_token: job.claim_token,
    });
    if (beginError) throw new DeliveryError('dispatch_check_failed', false, false);
    if (!allowed) return;
    dispatchStarted = true;
    const filename = `${s.document_type}-${String(s.document_number)
      .replace(/[^a-zA-Z0-9_-]/g, '-')
      .slice(0, 80)}.pdf`;
    const providerStarted = performance.now();
    const messageId = await sendWhatsappDocument(
      job.recipient,
      bytes,
      filename,
      job.caption,
      identity
    );
    const providerMs = performance.now() - providerStarted;
    const { error: finishError } = await db.rpc('finish_sale_document_delivery', {
      p_outbox_id: job.id,
      p_claim_token: job.claim_token,
      p_outcome: 'sent',
      p_provider_message_id: messageId,
    });
    if (finishError) throw new DeliveryError('delivery_record_failed', false, true);
    // Metadata only: no contact, caption, snapshot, base64 or PDF bytes in logs.
    console.info('sale_document_sent', {
      id: job.id,
      render_and_send_ms: Math.round(performance.now() - started),
      renderer_init_ms: Math.round(rendererInitMs),
      logo_ms: Math.round(logoMs),
      render_ms: Math.round(renderMs),
      provider_ms: Math.round(providerMs),
      bytes: bytes.length,
    });
  } catch (error) {
    const known = error instanceof DeliveryError ? error : null;
    const outcome =
      known?.accepted || (!known && dispatchStarted)
        ? 'unknown'
        : known && !known.permanent
          ? 'retry'
          : 'failed';
    const { error: finishError } = await db.rpc('finish_sale_document_delivery', {
      p_outbox_id: job.id,
      p_claim_token: job.claim_token,
      p_outcome: outcome,
      p_error:
        known?.message ??
        (dispatchStarted ? 'provider_acceptance_unknown' : 'pdf_preparation_failed'),
    });
    if (finishError) console.error('sale_document_finalization_failed', { id: job.id });
  }
}
