/**
 * WhatsApp quiet-hours helpers.
 *
 * Customer-facing WhatsApp messages generated by the system are only sent
 * between 08:00 and 19:00 EAT (Africa/Nairobi, UTC+3 year-round). Messages
 * generated outside that window are queued and flushed the next morning at
 * 08:00 EAT.
 *
 * These helpers use a fixed +3 hour offset rather than Intl timezone lookups
 * so behaviour is deterministic in tests and on servers where ICU data may be
 * trimmed.
 */

const QUIET_HOURS_START_EAT = 8; // 08:00 EAT
const QUIET_HOURS_END_EAT = 19; // 19:00 EAT
const EAT_OFFSET_HOURS = 3; // EAT = UTC+3

/**
 * Convert a UTC Date to an EAT (UTC+3) hour 0-23.
 */
export function getEatHour(date: Date): number {
  return (date.getUTCHours() + EAT_OFFSET_HOURS) % 24;
}

/**
 * True when the given UTC time falls inside the allowed WhatsApp send window
 * (08:00–19:00 EAT, inclusive start, exclusive end).
 */
export function isWithinWhatsAppWindow(date: Date = new Date()): boolean {
  const hour = getEatHour(date);
  return hour >= QUIET_HOURS_START_EAT && hour < QUIET_HOURS_END_EAT;
}

/**
 * Return the next 08:00 EAT flush time relative to the given UTC time.
 * If the reference time is already inside the send window, returns now.
 */
export function getNextWhatsAppFlushTime(date: Date = new Date()): Date {
  if (isWithinWhatsAppWindow(date)) {
    return new Date(date);
  }

  const currentEatHour = getEatHour(date);

  // Treat the timestamp as EAT by shifting it +3h. The UTC calendar fields of
  // the shifted date then represent the EAT calendar day.
  const eatTimestamp = date.getTime() + EAT_OFFSET_HOURS * 60 * 60 * 1000;
  const target = new Date(eatTimestamp);

  if (currentEatHour >= QUIET_HOURS_END_EAT) {
    // After 19:00 EAT: flush tomorrow morning (EAT calendar day).
    target.setUTCDate(target.getUTCDate() + 1);
  }

  // 08:00 EAT = 05:00 UTC on the same EAT calendar day.
  target.setUTCHours(QUIET_HOURS_START_EAT - EAT_OFFSET_HOURS, 0, 0, 0);
  return target;
}
