/**
 * Email generation utilities for customers
 *
 * Generates deterministic email addresses from phone numbers
 * when customers don't provide an email address.
 */

/**
 * Check if an email address appears to be auto-generated
 *
 * @param email - Email address to check
 * @returns true if email appears to be auto-generated
 */
export function isAutoGeneratedEmail(email: string): boolean {
  if (!email || typeof email !== 'string') {
    return false;
  }

  return email.endsWith('@pos.local') && email.startsWith('customer.');
}
