export interface CustomerStatementPrintRow {
  id: string;
  date: string;
  reference: string;
  description: string;
  debit: number;
  credit: number;
  balance: number;
}

export interface CustomerStatementPrintData {
  company: {
    name: string;
    address: string | null;
    logoUrl: string | null;
  };
  customerName: string;
  currency: string;
  generatedAt: string;
  rows: readonly CustomerStatementPrintRow[];
}

export interface RenderedCustomerStatement {
  title: string;
  html: string;
  styles: string;
}

const dateFormatter = new Intl.DateTimeFormat('en-KE', {
  year: 'numeric',
  month: 'short',
  day: 'numeric',
});

const amountFormatter = new Intl.NumberFormat('en-KE', {
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

export function renderCustomerStatement(
  data: CustomerStatementPrintData
): RenderedCustomerStatement {
  if (data.rows.length === 0) throw new Error('A statement requires at least one activity row.');

  const rows = [...data.rows].sort(
    (left, right) =>
      new Date(left.date).getTime() - new Date(right.date).getTime() ||
      left.id.localeCompare(right.id)
  );
  const oldest = rows[0]!;
  const newest = rows[rows.length - 1]!;
  const openingBalance = oldest.balance - oldest.debit + oldest.credit;
  const closingBalance = newest.balance;
  const totalDebits = rows.reduce((total, row) => total + row.debit, 0);
  const totalCredits = rows.reduce((total, row) => total + row.credit, 0);
  const logoUrl = safeImageUrl(data.company.logoUrl);
  const title = `${data.company.name} — Customer statement — ${data.customerName}`;

  const bodyRows = rows
    .map(
      row => `
        <tr>
          <td class="statement-date">${escapeText(formatDate(row.date))}</td>
          <td class="statement-reference">${escapeText(row.reference)}</td>
          <td class="statement-description">${escapeText(row.description)}</td>
          <td class="statement-amount">${row.debit > 0 ? formatAmount(row.debit) : '—'}</td>
          <td class="statement-amount">${row.credit > 0 ? formatAmount(row.credit) : '—'}</td>
          <td class="statement-amount statement-balance">${formatAmount(row.balance)}</td>
        </tr>`
    )
    .join('');

  const html = `
    <main class="print-template customer-statement">
      <header class="statement-header">
        <div class="statement-company">
          ${logoUrl ? `<img class="statement-logo" src="${escapeAttribute(logoUrl)}" alt="" />` : ''}
          <div>
            <h1>${escapeText(data.company.name)}</h1>
            ${data.company.address ? `<p>${escapeText(data.company.address)}</p>` : ''}
          </div>
        </div>
        <div class="statement-identity">
          <p class="statement-kicker">Customer statement</p>
          <p>Generated ${escapeText(formatDate(data.generatedAt))}</p>
        </div>
      </header>

      <section class="statement-meta" aria-label="Statement details">
        <div><span>Customer</span><strong>${escapeText(data.customerName)}</strong></div>
        <div><span>Period</span><strong>${escapeText(formatDate(oldest.date))} – ${escapeText(formatDate(newest.date))}</strong></div>
        <div><span>Currency</span><strong>${escapeText(data.currency)}</strong></div>
      </section>

      <section class="statement-summary" aria-label="Balance summary">
        ${summaryItem('Opening balance', openingBalance, data.currency)}
        ${summaryItem('Total charged', totalDebits, data.currency)}
        ${summaryItem('Total paid', totalCredits, data.currency)}
        ${summaryItem(accountState(closingBalance), closingBalance, data.currency, true)}
      </section>

      <table class="statement-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Reference</th>
            <th>Description</th>
            <th class="statement-amount">Debit</th>
            <th class="statement-amount">Credit</th>
            <th class="statement-amount">Balance</th>
          </tr>
        </thead>
        <tbody>${bodyRows}</tbody>
      </table>

      <footer class="statement-footer">
        <p>Amounts shown in ${escapeText(data.currency)}.</p>
        <p>Generated by Dukarun.</p>
      </footer>
    </main>`;

  return { title, html, styles: CUSTOMER_STATEMENT_STYLES };
}

function summaryItem(label: string, amount: number, currency: string, prominent = false): string {
  const displayedAmount = prominent ? Math.abs(amount) : amount;
  return `
    <div class="statement-summary-item${prominent ? ' statement-summary-closing' : ''}">
      <span>${escapeText(label)}</span>
      <strong>${escapeText(currency)} ${formatAmount(displayedAmount)}</strong>
    </div>`;
}

function accountState(balance: number): string {
  if (balance > 0) return 'Amount due';
  if (balance < 0) return 'Credit available';
  return 'Closing balance';
}

function formatDate(value: string): string {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : dateFormatter.format(date);
}

function formatAmount(value: number): string {
  return amountFormatter.format(value);
}

function safeImageUrl(value: string | null): string | null {
  if (!value) return null;
  try {
    const url = new URL(value);
    return url.protocol === 'https:' || url.protocol === 'http:' ? url.href : null;
  } catch {
    return null;
  }
}

function escapeAttribute(value: string): string {
  return escapeText(value);
}

function escapeText(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

const CUSTOMER_STATEMENT_STYLES = `
  @page { size: A4 portrait; margin: 14mm; }

  .customer-statement {
    width: 100%;
    color: #111827;
    font: 10pt/1.4 Arial, sans-serif;
  }

  .statement-header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 12mm;
    padding-bottom: 7mm;
    border-bottom: 0.5mm solid #111827;
  }

  .statement-company {
    display: flex;
    min-width: 0;
    align-items: center;
    gap: 4mm;
  }

  .statement-logo {
    display: block;
    width: auto;
    max-width: 32mm;
    height: auto;
    max-height: 18mm;
    object-fit: contain;
  }

  .statement-company h1 {
    margin: 0;
    font-size: 16pt;
    line-height: 1.15;
  }

  .statement-company p,
  .statement-identity p {
    margin: 1mm 0 0;
    color: #4b5563;
  }

  .statement-identity {
    flex: 0 0 auto;
    text-align: right;
  }

  .statement-identity .statement-kicker {
    margin: 0;
    color: #111827;
    font-size: 14pt;
    font-weight: 700;
  }

  .statement-meta {
    display: grid;
    grid-template-columns: 2fr 2fr 1fr;
    gap: 6mm;
    padding: 5mm 0;
    border-bottom: 0.2mm solid #d1d5db;
  }

  .statement-meta div,
  .statement-summary-item {
    min-width: 0;
  }

  .statement-meta span,
  .statement-summary-item span {
    display: block;
    margin-bottom: 1mm;
    color: #6b7280;
    font-size: 8pt;
    font-weight: 700;
    letter-spacing: 0.04em;
    text-transform: uppercase;
  }

  .statement-meta strong,
  .statement-summary-item strong {
    display: block;
    overflow-wrap: anywhere;
  }

  .statement-summary {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 0;
    margin: 5mm 0 6mm;
    border: 0.2mm solid #d1d5db;
  }

  .statement-summary-item {
    padding: 3mm;
    border-right: 0.2mm solid #d1d5db;
  }

  .statement-summary-item:last-child {
    border-right: 0;
  }

  .statement-summary-closing {
    background: #f3f4f6;
  }

  .statement-summary-closing strong {
    font-size: 11pt;
  }

  .statement-table {
    width: 100%;
    border-collapse: collapse;
    table-layout: fixed;
  }

  .statement-table thead {
    display: table-header-group;
  }

  .statement-table th {
    padding: 2.5mm 2mm;
    border-bottom: 0.4mm solid #374151;
    color: #374151;
    font-size: 8pt;
    letter-spacing: 0.03em;
    text-align: left;
    text-transform: uppercase;
  }

  .statement-table td {
    padding: 2.4mm 2mm;
    border-bottom: 0.2mm solid #e5e7eb;
    vertical-align: top;
  }

  .statement-table tr {
    break-inside: avoid;
    page-break-inside: avoid;
  }

  .statement-date { width: 17mm; white-space: nowrap; }
  .statement-reference { width: 27mm; overflow-wrap: anywhere; }
  .statement-description { overflow-wrap: anywhere; }
  .statement-amount {
    width: 23mm;
    text-align: right !important;
    white-space: nowrap;
    font-variant-numeric: tabular-nums;
  }
  .statement-balance { font-weight: 700; }

  .statement-footer {
    display: flex;
    justify-content: space-between;
    gap: 8mm;
    margin-top: 8mm;
    padding-top: 3mm;
    border-top: 0.2mm solid #d1d5db;
    color: #6b7280;
    font-size: 8pt;
  }

  @media print {
    .customer-statement { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  }
`;
