import { Injectable } from '@nestjs/common';
import {
  Administrator,
  AdministratorService,
  Channel,
  ChannelService,
  CurrencyCode,
  RequestContext,
  TransactionalConnection,
  User,
  Zone,
  ZoneService,
} from '@vendure/core';
import { IsNull } from 'typeorm';
import { RegistrationInput } from '../registration.service';

/**
 * Registration Validator Service
 *
 * Handles pre-creation validation for registration data:
 * - Currency code validation
 * - Channel code uniqueness
 * - Default zones availability
 */
@Injectable()
export class RegistrationValidatorService {
  constructor(
    private readonly channelService: ChannelService,
    private readonly administratorService: AdministratorService,
    private readonly connection: TransactionalConnection,
    private readonly zoneService: ZoneService
  ) { }

  /**
   * Validate registration input before provisioning
   * Throws errors with REGISTRATION_ prefix if validation fails
   */
  async validateInput(
    ctx: RequestContext,
    registrationData: RegistrationInput,
    existingUser?: User
  ): Promise<void> {
    // Validate currency code
    if (!Object.values(CurrencyCode).includes(registrationData.currency as CurrencyCode)) {
      throw new Error(
        `REGISTRATION_CURRENCY_INVALID: Invalid currency code "${registrationData.currency}". Must be a valid CurrencyCode enum value.`
      );
    }

    // companyCode is not part of input - it's always generated by channel-provisioner
    // No validation needed here

    // Validate default zones are configured
    await this.validateDefaultZones(ctx);

    // Validate admin email uniqueness if provided
    if (registrationData.adminEmail) {
      await this.validateAdminEmailUniqueness(ctx, registrationData.adminEmail, existingUser);
    }
  }

  /**
   * Get default channel with zones for new channel creation
   */
  async getDefaultChannel(ctx: RequestContext): Promise<Channel> {
    // First try to get the current channel
    if (ctx.channelId) {
      const channel = await this.channelService.findOne(ctx, ctx.channelId);
      if (channel && channel.defaultShippingZone && channel.defaultTaxZone) {
        return channel;
      }
    }

    // Get the first available channel as fallback
    const channels = await this.channelService.findAll(ctx);
    const defaultChannel = channels.items[0];

    if (!defaultChannel) {
      throw new Error(
        `REGISTRATION_ZONES_MISSING: No channels found in system. Please create a default channel first.`
      );
    }

    return defaultChannel;
  }

  /**
   * Check if company code is available (not taken)
   * Returns true if available, false if taken
   */
  async checkCompanyCodeAvailability(
    ctx: RequestContext,
    companyCode: string
  ): Promise<boolean> {
    // Use ChannelService.findAll() to check for existing channel with same code
    // Note: ChannelService doesn't provide findOne by code, so we use findAll and filter
    const channels = await this.channelService.findAll(ctx);
    const existingChannel = channels.items.find(ch => ch.code === companyCode);

    // Return true if available (no existing channel), false if taken
    return !existingChannel;
  }

  /**
   * Validate channel code uniqueness using ChannelService
   */
  private async validateChannelCodeUniqueness(
    ctx: RequestContext,
    companyCode: string
  ): Promise<void> {
    const isAvailable = await this.checkCompanyCodeAvailability(ctx, companyCode);
    if (!isAvailable) {
      throw new Error(
        `REGISTRATION_CHANNEL_CODE_EXISTS: Channel with code "${companyCode}" already exists. Please choose a different company code.`
      );
    }
  }

  private async validateDefaultZones(ctx: RequestContext): Promise<void> {
    const defaultChannel = await this.getDefaultChannel(ctx);

    if (!defaultChannel.defaultShippingZone || !defaultChannel.defaultTaxZone) {
      throw new Error(
        `REGISTRATION_ZONES_MISSING: Default zones not configured. ` +
        `Please set up shipping and tax zones in the default channel first. ` +
        `Navigate to Settings → Channels → Default Channel and configure defaultShippingZone and defaultTaxZone.`
      );
    }
  }

  /**
   * Validate admin email uniqueness using AdministratorService
   * Uses repository for loading with relations (AdministratorService limitation)
   */
  async validateAdminEmailUniqueness(
    ctx: RequestContext,
    email: string,
    existingUser?: User,
    phoneNumber?: string
  ): Promise<void> {
    // Note: AdministratorService doesn't provide findOne by email with relations,
    // so we use repository for this lookup (documented limitation)
    const adminRepo = this.connection.getRepository(ctx, Administrator);
    const existingAdmin = await adminRepo.findOne({
      where: {
        emailAddress: email,
        deletedAt: IsNull() // Exclude soft-deleted administrators
      },
      relations: ['user'],
    });

    if (existingAdmin) {
      // If admin exists, check if it belongs to the same user
      // Case 1: We have the existing user entity (from provisionCustomer)
      if (existingUser && existingAdmin.user && existingAdmin.user.id === existingUser.id) {
        return; // Same user, allow using same email
      }

      // Case 2: We have the phone number (from requestRegistrationOTP)
      // Check if the existing admin is linked to a user with this phone number
      if (phoneNumber && existingAdmin.user && existingAdmin.user.identifier === phoneNumber) {
        return; // Same user (by phone), allow using same email
      }

      throw new Error(
        `REGISTRATION_EMAIL_EXISTS: An administrator with email "${email}" already exists. Please use a different email address.`
      );
    }
  }

  /**
   * Get Kenya zone by name using ZoneService
   * Uses ZoneService.findAll() and filters by name (ZoneService doesn't provide findByName)
   */
  async getKenyaZone(ctx: RequestContext): Promise<Zone> {
    // Use ZoneService.findAll() to get all zones, then filter by name
    // Note: ZoneService doesn't provide findOne by name, so we use findAll and filter
    const zones = await this.zoneService.findAll(ctx);
    const kenyaZone = zones.items.find(z => z.name === 'Kenya');

    if (!kenyaZone) {
      throw new Error(
        `REGISTRATION_KENYA_ZONE_MISSING: Kenya zone not found. ` +
        `Please create a zone named "Kenya" in Settings → Zones.`
      );
    }

    return kenyaZone;
  }
}
