import { graphql } from './generated';

/**
 * Shop-API operations for the public storefront. Types are generated into ./generated by codegen
 * (`npm run codegen -w @dukarun/storefront`, backend must be running).
 */

export const STOREFRONT = graphql(`
  query Storefront($slug: String!) {
    storefront(slug: $slug) {
      channelToken
      name
      slug
      whatsappNumber
      catalogueVisible
      logo {
        id
        preview
      }
    }
  }
`);

export const PUBLIC_STOREFRONTS = graphql(`
  query PublicStorefronts {
    publicStorefronts {
      name
      slug
      logo {
        id
        preview
      }
    }
  }
`);

export const SEARCH_PRODUCTS = graphql(`
  query SearchProducts($input: SearchInput!) {
    search(input: $input) {
      totalItems
      items {
        productId
        productName
        slug
        description
        productAsset {
          id
          preview
        }
        priceWithTax {
          ... on PriceRange {
            min
            max
          }
          ... on SinglePrice {
            value
          }
        }
        currencyCode
        inStock
        facetValueIds
      }
      facetValues {
        count
        facetValue {
          id
          name
          facet {
            id
            name
            code
          }
        }
      }
    }
  }
`);

export const PRODUCT_DETAIL = graphql(`
  query ProductDetail($slug: String!) {
    product(slug: $slug) {
      id
      name
      slug
      description
      featuredAsset {
        id
        preview
      }
      assets {
        id
        preview
      }
      facetValues {
        id
        name
        facet {
          id
          code
          name
        }
      }
      variants {
        id
        name
        sku
        priceWithTax
        currencyCode
        stockLevel
      }
    }
  }
`);

export const COLLECTION_DETAIL = graphql(`
  query CollectionDetail($slug: String!) {
    collection(slug: $slug) {
      id
      name
      slug
      description
      featuredAsset {
        id
        preview
      }
    }
  }
`);

export const COLLECTIONS = graphql(`
  query Collections($options: CollectionListOptions) {
    collections(options: $options) {
      totalItems
      items {
        id
        name
        slug
        featuredAsset {
          id
          preview
        }
      }
    }
  }
`);
