import type { WorkbookSnapshot } from './product-workbook';

/** Small realistic catalogue for workbook contract tests; all identities are fictional. */
export function workbookFixture(): WorkbookSnapshot {
  const id = (n: number) => `85000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
  const updated = '2026-09-16T09:00:00.000Z';
  return {
    company_id: id(1),
    company_name: 'Workbook Shop',
    exported_at: updated,
    location: { id: id(2), code: 'MAIN', name: 'Main shop' },
    capabilities: { stock: true, financial: true },
    manufacturers: [{ id: id(3), name: 'Soap Works', active: true, updated_at: updated }],
    taxes: [{ id: id(4), code: 'STANDARD' }],
    products: [
      {
        id: id(5),
        name: 'Soap',
        barcode: null,
        active: true,
        manufacturer_id: id(3),
        tax_category_id: null,
        updated_at: updated,
      },
      {
        id: id(6),
        name: 'Rice',
        barcode: null,
        active: true,
        manufacturer_id: null,
        tax_category_id: null,
        updated_at: updated,
      },
    ],
    variants: [
      {
        id: id(7),
        product_id: id(5),
        name: '250g',
        sku: 'SOAP250',
        barcode: '600001',
        kind: 'good',
        price: 50,
        wholesale_price: 45,
        stock_unit: 'bar',
        track_inventory: true,
        allow_fractional: false,
        active: true,
        updated_at: updated,
      },
      {
        id: id(8),
        product_id: id(5),
        name: '500g',
        sku: 'SOAP500',
        barcode: '600002',
        kind: 'good',
        price: 95,
        wholesale_price: 88,
        stock_unit: 'bar',
        track_inventory: true,
        allow_fractional: false,
        active: true,
        updated_at: updated,
      },
      {
        id: id(9),
        product_id: id(6),
        name: 'Default',
        sku: 'RICE',
        barcode: null,
        kind: 'good',
        price: 160,
        wholesale_price: null,
        stock_unit: 'kg',
        track_inventory: true,
        allow_fractional: true,
        active: true,
        updated_at: updated,
      },
    ],
    packs: [
      {
        id: id(10),
        variant_id: id(7),
        name: 'Box',
        units_per_pack: 12,
        sale_price: 540,
        barcode: '600012',
        active: true,
      },
    ],
    stock: [
      {
        variant_id: id(7),
        quantity: 48,
        value: 1536,
        batch: {
          id: id(11),
          remaining: 48,
          unit_cost: 32,
          remaining_cost: 1536,
          batch_number: 'SOAP-01',
          expiry_date: null,
        },
      },
      {
        variant_id: id(8),
        quantity: 24,
        value: 1632,
        batch: {
          id: id(12),
          remaining: 24,
          unit_cost: 68,
          remaining_cost: 1632,
          batch_number: null,
          expiry_date: null,
        },
      },
      {
        variant_id: id(9),
        quantity: 36.5,
        value: 4015,
        batch: {
          id: id(13),
          remaining: 36.5,
          unit_cost: 110,
          remaining_cost: 4015,
          batch_number: null,
          expiry_date: null,
        },
      },
    ],
  };
}
